port: 4000
markdown: kramdown
permalink: '/:title'
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
title: Portfolio Jekyll Theme
description: Powered by Jekyll and GitHub Pages
author: Paul Le
baseurl: ''
url: ''
